{
 "title": "OpenStack Octavia Amphora Load Balancer",
 "description": "A dashboard for OpenStack Octavia load balancer metrics",
 "tags": [
  "OpenStack",
  "Octavia",
  "LoadBalancer"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "lb",
    "label": "Load Balancer",
    "query": {
     "query": "label_values(octavia_loadbalancer_cpu, instance)"
    }
   },
   {
    "name": "listener",
    "label": "Listener",
    "query": {
     "query": "label_values(octavia_listener_status{instance=~'${lb:raw}', listener!=\"native-prometheus\"}, listener)"
    }
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(octavia_pool_status{instance=~'${lb:raw}'}, pool)"
    }
   },
   {
    "name": "member",
    "label": "Member",
    "query": {
     "query": "label_values(octavia_member_status{instance=~'${lb:raw}', pool=~'${pool:raw}'}, member)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "gauge",
   "description": "Percent CPU utilization. Displays the maximum value if multiple load balancers are selected.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(octavia_loadbalancer_cpu{instance=~'${lb}'})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Percent RAM utilization. Displays the maximum value if multiple load balancers are selected. ",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(octavia_loadbalancer_memory{instance=~'${lb}'})"
    }
   ]
  },
  {
   "title": "Load Balancer(s) CPS",
   "type": "gauge",
   "description": "Instant read of the current number of connections per second across the selected load balancers.",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(octavia_loadbalancer_current_connection_rate{instance=~'${lb}'})",
     "legendFormat": "octavia_loadbalancer_current_connection_rate"
    },
    {
     "expr": "sum(octavia_loadbalancer_max_connections{instance=~'${lb}'})",
     "legendFormat": "octavia_loadbalancer_max_connections"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "description": "Instant read of the current throughput across the selected load balancers.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(octavia_listener_bytes_in_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])*8)",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(octavia_listener_bytes_out_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])*8)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Member Status",
   "type": "piechart",
   "description": "Shows the percentage of members in each state across the selected load balancers.\nOptions are: Online, Offline (admin down/disabled),  Error, or Draining.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(octavia_member_status{instance=~'${lb}',pool=~'${pool}',member=~'${member}'} == 0)",
     "legendFormat": "Error"
    },
    {
     "expr": "count(octavia_member_status{instance=~'${lb}',pool=~'${pool}',member=~'${member}'} == 1)",
     "legendFormat": "Online"
    },
    {
     "expr": "count(octavia_member_status{instance=~'${lb}',pool=~'${pool}',member=~'${member}'} == 2)",
     "legendFormat": "Offline"
    },
    {
     "expr": "count(octavia_member_status{instance=~'${lb}',pool=~'${pool}',member=~'${member}'} == 3)",
     "legendFormat": "Draining"
    }
   ]
  },
  {
   "title": "Total in Selection",
   "type": "stat",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(octavia_loadbalancer_cpu{instance=~'${lb}'})",
     "legendFormat": "Load Balancers"
    },
    {
     "expr": "count(octavia_listener_status{instance=~'${lb}',listener=~'${listener}'})",
     "legendFormat": "Listeners"
    },
    {
     "expr": "count(octavia_pool_status{instance=~'${lb}',listener=~'${listener}',pool=~'${pool}'})",
     "legendFormat": "Pools"
    },
    {
     "expr": "count(group by (member) (octavia_member_status{instance=~'${lb}',listener=~'${listener}',pool=~'${pool}',member=~'${member}'}))",
     "legendFormat": "Members"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(irate(octavia_listener_http_responses_total{instance=~\"$lb\",listener=~\"$listener\"}[$__rate_interval])) by (code)",
     "legendFormat": "Front {{ code }}"
    },
    {
     "expr": "sum(irate(octavia_pool_http_responses_total{instance=~\"$lb\",pool=~\"$pool\"}[$__rate_interval])) by (code)",
     "legendFormat": "Pool {{ code }}"
    }
   ]
  },
  {
   "title": "Peak Rates",
   "type": "stat",
   "description": "The maximum observed connections per second and requests per second across the selected load balancers. Values may reset on load balancer configuration change or failover.",
   "gridPos": { "h": 10, "w": 4, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(octavia_loadbalancer_max_connection_rate{instance=~'${lb}'})",
     "legendFormat": "Connections Per Second"
    },
    {
     "expr": "max(octavia_loadbalancer_max_ssl_rate{instance=~'${lb}'})",
     "legendFormat": "TLS Connections Per Second"
    },
    {
     "expr": "max(sum by (instance) (octavia_listener_http_requests_rate_max{instance=~'${lb}', listener=~'${listener}'}))",
     "legendFormat": "HTTP Requests Per Second"
    }
   ]
  },
  {
   "title": "Load Balancer Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "octavia_loadbalancer_cpu{instance=~'${lb}'}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "octavia_loadbalancer_memory{instance=~'${lb}'}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Concurrent Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "irate(octavia_loadbalancer_connections_total{instance=~'${lb}'}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "irate(octavia_loadbalancer_ssl_connections_total{instance=~'${lb}'}[$__rate_interval])",
       "legendFormat": "TLS {{ instance }}"
      }
     ]
    },
    {
     "title": "Concurrent Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "irate(octavia_loadbalancer_requests_total{instance=~'${lb}'}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "TLS Key Rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "octavia_loadbalancer_current_frontend_ssl_key_rate{instance=~'${lb}'}",
       "legendFormat": "Listener {{ instance }}"
      },
      {
       "expr": "octavia_loadbalancer_current_backend_ssl_key_rate{instance=~'${lb}'}",
       "legendFormat": "Pool {{ instance }}"
      }
     ]
    },
    {
     "title": "TLS Session Reuse",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "octavia_loadbalancer_frontent_ssl_reuse{instance=~'${lb}'}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "TLS Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "irate(octavia_loadbalancer_ssl_cache_lookups_total{instance=~'${lb}'}[$__rate_interval])",
       "legendFormat": "Lookups {{ instance }}"
      },
      {
       "expr": "irate(octavia_loadbalancer_ssl_cache_misses_total{instance=~'${lb}'}[$__rate_interval])",
       "legendFormat": "Miss {{ instance }}"
      }
     ]
    },
    {
     "title": "Compression Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(octavia_loadbalancer_http_comp_bytes_in_total{instance=~'${lb}'}[$__rate_interval])",
       "legendFormat": "In {{ instance }}"
      },
      {
       "expr": "irate(octavia_loadbalancer_http_comp_bytes_out_total{instance=~'${lb}'}[$__rate_interval])",
       "legendFormat": "Out {{ instance }}"
      }
     ]
    },
    {
     "title": "Active Listeners",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "count by (instance) (octavia_listener_status{instance=~'${lb}'})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Logs Dropped",
     "type": "timeseries",
     "description": "Traffic flow logs dropped due to system load.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "irate(octavia_loadbalancer_dropped_logs_total{instance=~'${lb}'}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "octavia_memory_pool_allocated_bytes{instance=~'${lb}'}",
       "legendFormat": "Allocated {{ instance }}"
      },
      {
       "expr": "octavia_memory_pool_used_bytes{instance=~'${lb}'}",
       "legendFormat": "Used {{ instance }}"
      },
      {
       "expr": "irate(octavia_memory_pool_failures_total{instance=~'${lb}'}[$__rate_interval])",
       "legendFormat": "Failures {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Listener Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Listener Status",
     "type": "piechart",
     "description": "The current listener status. 0=Offline, 1=Online, 2=Degraded (at the configured capacity).",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(octavia_listener_status{instance=~'${lb}',listener=~'${listener}'} == 0)",
       "legendFormat": "Offline"
      },
      {
       "expr": "count(octavia_listener_status{instance=~'${lb}',listener=~'${listener}'} == 1)",
       "legendFormat": "Online"
      },
      {
       "expr": "count(octavia_listener_status{instance=~'${lb}',listener=~'${listener}'} == 2)",
       "legendFormat": "Degraded"
      }
     ]
    },
    {
     "title": "Peak Values",
     "type": "stat",
     "description": "The maximum observed concurrent sessions, sessions per second, and requests per second across the selected listeners. Values may reset on load balancer configuration change or failover.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(octavia_listener_max_sessions{instance=~'${lb}',listener=~'${listener}'})",
       "legendFormat": "Concurrent Sessions"
      },
      {
       "expr": "max(octavia_listener_max_session_rate{instance=~'${lb}',listener=~'${listener}'})",
       "legendFormat": "Sessions Per Second"
      },
      {
       "expr": "max(octavia_listener_http_requests_rate_max{instance=~'${lb}',listener=~'${listener}'})",
       "legendFormat": "Requests Per Second"
      }
     ]
    },
    {
     "title": "HTTP Response Status Codes",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='1xx'})",
       "legendFormat": "1xx"
      },
      {
       "expr": "sum(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='2xx'})",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='3xx'})",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='4xx'})",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='5xx'})",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='other'})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "HTTP Response Status Codes",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='1xx'})",
       "legendFormat": "1xx"
      },
      {
       "expr": "sum(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='2xx'})",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='3xx'})",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='4xx'})",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='5xx'})",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='other'})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "HTTP Response Status Code Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='1xx'}[$__rate_interval]))",
       "legendFormat": "1xx"
      },
      {
       "expr": "sum(irate(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='2xx'}[$__rate_interval]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(irate(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='3xx'}[$__rate_interval]))",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(irate(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='4xx'}[$__rate_interval]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(irate(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='5xx'}[$__rate_interval]))",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(irate(octavia_listener_http_responses_total{instance=~'${lb}',listener=~'${listener}',code='other'}[$__rate_interval]))",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Concurrent Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "irate(octavia_listener_connections_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])",
       "legendFormat": "{{ listener }}"
      }
     ]
    },
    {
     "title": "Concurrent Sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "irate(octavia_listener_sessions_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])",
       "legendFormat": "{{ listener }}"
      }
     ]
    },
    {
     "title": "Listener Throughput In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(octavia_listener_bytes_in_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])",
       "legendFormat": "{{ listener }}"
      }
     ]
    },
    {
     "title": "Listener Throughput Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(octavia_listener_bytes_out_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])",
       "legendFormat": "{{ listener }}"
      }
     ]
    },
    {
     "title": "Denied Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "irate(octavia_listener_denied_connections_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])",
       "legendFormat": "{{ listener }}"
      }
     ]
    },
    {
     "title": "Denied Sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "irate(octavia_listener_denied_sessions_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])",
       "legendFormat": "{{ listener }}"
      }
     ]
    },
    {
     "title": "Denied Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "irate(octavia_listener_requests_denied_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])",
       "legendFormat": "{{ listener }}"
      }
     ]
    },
    {
     "title": "Denied Responses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "irate(octavia_listener_responses_denied_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])",
       "legendFormat": "{{ listener }}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "irate(octavia_listener_http_requests_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])",
       "legendFormat": "{{ listener }}"
      }
     ]
    },
    {
     "title": "Request Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "irate(octavia_listener_request_errors_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])",
       "legendFormat": "{{ listener }}"
      }
     ]
    },
    {
     "title": "HTTP Cache Hit Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(irate(octavia_listener_http_cache_hits_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])/irate(octavia_listener_http_cache_lookups_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval]))*100",
       "legendFormat": "{{ listener }}"
      }
     ]
    },
    {
     "title": "HTTP Compressed Responses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_listener_http_comp_responses_total{instance=~'${lb}',listener=~'${listener}'}[$__rate_interval])",
       "legendFormat": "{{ listener }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pool Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool Status",
     "type": "piechart",
     "description": "The current pool status. 0=Error, 1=Online",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(octavia_pool_status{instance=~'${lb}',pool=~'${pool}'} == 0)",
       "legendFormat": "Error"
      },
      {
       "expr": "count(octavia_pool_status{instance=~'${lb}',pool=~'${pool}'} == 1)",
       "legendFormat": "Online"
      }
     ]
    },
    {
     "title": "Peak Values",
     "type": "stat",
     "description": "The maximum observed concurrent sessions, sessions per second, and queued requests across the selected pools. Values may reset on load balancer configuration change or failover.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(octavia_pool_max_sessions{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Concurrent Sessions"
      },
      {
       "expr": "max(octavia_pool_max_session_rate{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Sessions Per Second"
      },
      {
       "expr": "max(octavia_pool_max_queue{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Queued Requests"
      }
     ]
    },
    {
     "title": "HTTP Response Status Codes",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='1xx'})",
       "legendFormat": "1xx"
      },
      {
       "expr": "sum(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='2xx'})",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='3xx'})",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='4xx'})",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='5xx'})",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='other'})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "HTTP Response Status Codes",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='1xx'})",
       "legendFormat": "1xx"
      },
      {
       "expr": "sum(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='2xx'})",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='3xx'})",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='4xx'})",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='5xx'})",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='other'})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "HTTP Response Status Code Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='1xx'}[$__rate_interval]))",
       "legendFormat": "1xx"
      },
      {
       "expr": "sum(irate(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='2xx'}[$__rate_interval]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(irate(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='3xx'}[$__rate_interval]))",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(irate(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='4xx'}[$__rate_interval]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(irate(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='5xx'}[$__rate_interval]))",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(irate(octavia_pool_http_responses_total{instance=~'${lb}',pool=~'${pool}',code='other'}[$__rate_interval]))",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Client Abort Rate",
     "type": "timeseries",
     "description": "The rate at which the client aborted the connection. I.e. the user closed the browser window.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "irate(octavia_pool_client_aborts_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Member Server Abort Rate",
     "type": "timeseries",
     "description": "Rate that the backend member servers are aborting connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "irate(octavia_pool_member_aborts_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Concurrent Sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "irate(octavia_pool_sessions_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Queued Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "octavia_pool_current_queue{instance=~'${lb}',pool=~'${pool}'}",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Connection Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_pool_connection_attempts_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Connection Reuse Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_pool_connection_reuses_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Throughput In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(octavia_pool_bytes_in_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Throughput Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(octavia_pool_bytes_out_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Member Dispatches",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (member) (octavia_member_loadbalanced_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Pool HTTP Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_pool_http_requests_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Members",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "octavia_pool_active_members{instance=~'${lb}',pool=~'${pool}'}",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Backup Members",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "octavia_pool_backup_members{instance=~'${lb}',pool=~'${pool}'}",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Requests Denied",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_pool_requests_denied_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Responses Denied",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_pool_responses_denied_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Connection Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_pool_connection_errors_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Response Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_pool_response_errors_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Retry Warnings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_pool_retry_warnings_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Redispatch Warnings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_pool_redispatch_warnings_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Up/Down Transition Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_pool_check_up_down_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool Up/Down Summary",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(octavia_pool_check_up_down_total{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Total Transitions"
      },
      {
       "expr": "max(octavia_pool_check_last_change_seconds{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Maximum Time Since Last Transition"
      },
      {
       "expr": "max(octavia_pool_downtime_seconds_total{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Maximum Downtime"
      }
     ]
    },
    {
     "title": "Pool HTTP Cache Hit Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(irate(octavia_pool_http_cache_hits_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])/irate(octavia_pool_http_cache_lookups_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval]))*100",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Pool HTTP Compressed Responses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_pool_http_comp_responses_total{instance=~'${lb}',pool=~'${pool}'}[$__rate_interval])",
       "legendFormat": "{{ pool }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pool Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Maximum Times",
     "type": "stat",
     "description": "The current maximum time across the selected pools. Values may reset on load balancer configuration change or failover.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(octavia_pool_queue_time_average_seconds{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Queue Time"
      },
      {
       "expr": "max(octavia_pool_connect_time_average_seconds{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Connect Time"
      },
      {
       "expr": "max(octavia_pool_response_time_average_seconds{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Response Time"
      },
      {
       "expr": "max(octavia_pool_total_time_average_seconds{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Total Time"
      }
     ]
    },
    {
     "title": "Peak Times",
     "type": "stat",
     "description": "The maximum observed time across the selected pools. Values may reset on load balancer configuration change or failover.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(octavia_pool_max_queue_time_seconds{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Queue Time"
      },
      {
       "expr": "max(octavia_pool_max_connect_time_seconds{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Connect Time"
      },
      {
       "expr": "max(octavia_pool_max_response_time_seconds{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Response Time"
      },
      {
       "expr": "max(octavia_pool_max_total_time_seconds{instance=~'${lb}',pool=~'${pool}'})",
       "legendFormat": "Total Time"
      }
     ]
    },
    {
     "title": "Average Queue Time",
     "type": "timeseries",
     "description": "Average queue time for last 1024 successful connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "octavia_pool_queue_time_average_seconds{instance=~'${lb}',pool=~'${pool}'}",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Average Connect Time",
     "type": "timeseries",
     "description": "Average connect time for last 1024 successful connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "octavia_pool_connect_time_average_seconds{instance=~'${lb}',pool=~'${pool}'}",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "description": "Average response time for last 1024 successful connections. Inclusive of member server time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "octavia_pool_response_time_average_seconds{instance=~'${lb}',pool=~'${pool}'}",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Average Total Time",
     "type": "timeseries",
     "description": "Average total time for last 1024 successful connections. Inclusive of member server time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "octavia_pool_total_time_average_seconds{instance=~'${lb}',pool=~'${pool}'}",
       "legendFormat": "{{ pool }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Member Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Member Status",
     "type": "piechart",
     "description": "Shows the percentage of members in each state across the selected load balancers.\nOptions are: Online, Offline (admin down/disabled),  Error, or Draining.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(octavia_member_status{instance=~'${lb}',pool=~'${pool}',member=~'${member}'} == 0)",
       "legendFormat": "Error"
      },
      {
       "expr": "count(octavia_member_status{instance=~'${lb}',pool=~'${pool}',member=~'${member}'} == 1)",
       "legendFormat": "Online"
      },
      {
       "expr": "count(octavia_member_status{instance=~'${lb}',pool=~'${pool}',member=~'${member}'} == 2)",
       "legendFormat": "Offline"
      },
      {
       "expr": "count(octavia_member_status{instance=~'${lb}',pool=~'${pool}',member=~'${member}'} == 3)",
       "legendFormat": "Draining"
      }
     ]
    },
    {
     "title": "Peak Values",
     "type": "stat",
     "description": "The maximum observed concurrent sessions, sessions per second, and queued requests across the selected members. Values may reset on load balancer configuration change or failover.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(octavia_member_max_sessions{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Concurrent Sessions"
      },
      {
       "expr": "max(octavia_member_max_session_rate{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Sessions Per Second"
      },
      {
       "expr": "max(octavia_member_max_queue{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Queued Requests"
      }
     ]
    },
    {
     "title": "HTTP Response Status Codes",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='1xx'})",
       "legendFormat": "1xx"
      },
      {
       "expr": "sum(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='2xx'})",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='3xx'})",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='4xx'})",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='5xx'})",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='other'})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "HTTP Response Status Codes",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='1xx'})",
       "legendFormat": "1xx"
      },
      {
       "expr": "sum(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='2xx'})",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='3xx'})",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='4xx'})",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='5xx'})",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='other'})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "HTTP Response Status Code Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='1xx'}[$__rate_interval]))",
       "legendFormat": "1xx"
      },
      {
       "expr": "sum(irate(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='2xx'}[$__rate_interval]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(irate(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='3xx'}[$__rate_interval]))",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(irate(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='4xx'}[$__rate_interval]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(irate(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='5xx'}[$__rate_interval]))",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(irate(octavia_member_http_responses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}',code='other'}[$__rate_interval]))",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Client Abort Rate",
     "type": "timeseries",
     "description": "The rate at which the client aborted the connection. I.e. the user closed the browser window.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "irate(octavia_member_client_aborts_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Server Abort Rate",
     "type": "timeseries",
     "description": "Rate that the backend member servers are aborting connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "irate(octavia_member_server_aborts_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Concurrent Sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "irate(octavia_member_sessions_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Queued Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "octavia_member_current_queue{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Throughput In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(octavia_member_bytes_in_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Throughput Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(octavia_member_bytes_out_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Connection Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_member_connection_attempts_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Connection Reuse Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_member_connection_reuses_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Dispatches",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (member) (octavia_member_loadbalanced_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Idle Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "octavia_member_idle_connections_current{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Responses Denied",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_member_responses_denied_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Connection Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_member_connection_errors_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Response Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_member_response_errors_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Retry Warnings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_member_retry_warnings_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Redispatch Warnings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_member_redispatch_warnings_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Health Check Failure Rate",
     "type": "timeseries",
     "description": "Failed check rate. (Only counts checks failed when the member is up).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_member_check_failures_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Up/Down Transition Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(octavia_member_check_up_down_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}[$__rate_interval])",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Up/Down Summary",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(octavia_member_check_up_down_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Total Transitions"
      },
      {
       "expr": "max(octavia_member_check_last_change_seconds{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Maximum Time Since Last Transition"
      },
      {
       "expr": "max(octavia_member_downtime_seconds_total{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Maximum Downtime"
      }
     ]
    },
    {
     "title": "Member Weight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "octavia_member_weight{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Member Throttle",
     "type": "timeseries",
     "description": "Current throttle percentage for the member, when slowstart is active, or no value if not in slowstart.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "octavia_member_current_throttle{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}",
       "legendFormat": "{{ member }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Member Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Maximum Times",
     "type": "stat",
     "description": "The current maximum time across the selected members. Values may reset on load balancer configuration change or failover.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(octavia_member_queue_time_average_seconds{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Queue Time"
      },
      {
       "expr": "max(octavia_member_connect_time_average_seconds{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Connect Time"
      },
      {
       "expr": "max(octavia_member_response_time_average_seconds{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Response Time"
      },
      {
       "expr": "max(octavia_member_total_time_average_seconds{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Total Time"
      }
     ]
    },
    {
     "title": "Peak Times",
     "type": "stat",
     "description": "The maximum observed time across the selected members. Values may reset on load balancer configuration change or failover.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(octavia_member_max_queue_time_seconds{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Queue Time"
      },
      {
       "expr": "max(octavia_member_max_connect_time_seconds{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Connect Time"
      },
      {
       "expr": "max(octavia_member_max_response_time_seconds{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Response Time"
      },
      {
       "expr": "max(octavia_member_max_total_time_seconds{instance=~'${lb}',pool=~'${pool}',member=~'${member}'})",
       "legendFormat": "Total Time"
      }
     ]
    },
    {
     "title": "Average Queue Time",
     "type": "timeseries",
     "description": "Average queue time for last 1024 successful connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "octavia_member_queue_time_average_seconds{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Average Connect Time",
     "type": "timeseries",
     "description": "Average connect time for last 1024 successful connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "octavia_member_connect_time_average_seconds{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "description": "Average response time for last 1024 successful connections. Inclusive of member server time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "octavia_member_response_time_average_seconds{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}",
       "legendFormat": "{{ member }}"
      }
     ]
    },
    {
     "title": "Average Total Time",
     "type": "timeseries",
     "description": "Average total time for last 1024 successful connections. Inclusive of member server time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "octavia_member_total_time_average_seconds{instance=~'${lb}',pool=~'${pool}',member=~'${member}'}",
       "legendFormat": "{{ member }}"
      }
     ]
    }
   ]
  }
 ]
}